<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DSK-4052" failures="0" tests="1" name="com.amt.test.LOU.Lead_broker_individual_flow" time="33.664" errors="1" timestamp="2023-06-16T14:40:14 IST" skipped="0">
  <testcase classname="com.amt.test.LOU.Lead_broker_individual_flow" name="broker_create_opportunity_individual" time="33.664">
    <error message="Cannot invoke &quot;String.equalsIgnoreCase(String)&quot; because &quot;name&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "name" is null
at org.apache.poi.xssf.usermodel.XSSFWorkbook.getSheet(XSSFWorkbook.java:1169)
at com.amt.testUtil.GetExcelFormulaValue.get_string_value_without_formula(GetExcelFormulaValue.java:91)
at com.amt.pages.Opportunities.opp_search_textbox(Opportunities.java:814)
at com.amt.test.LOU.Lead_broker_individual_flow.broker_create_opportunity_individual(Lead_broker_individual_flow.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- broker_create_opportunity_individual -->
  <system-out>
    <![CDATA[<b>Clicked on Opportunity link from Menu </b> <br />
<br>----------Screenshot---------<br>
<img src="D:\LOU\AMT_LOU\target\surefire-reports\html\failure_screenshots\broker_create_opportunity_individual_16_06_2023_02_40_14.png" height="800" width="1000">]]>
  </system-out>
</testsuite> <!-- com.amt.test.LOU.Lead_broker_individual_flow -->
